### ISSUE TITLE
Mention in README that Maven 3.0.5 is required for rebuilding

### ISSUE THREAD

**Issue by orospakr** [jakenjarvis/Android-OrmLiteContentProvider#12]
Attempts to build with 3.1 blow up with:

`java.lang.NoClassDefFoundError: Lorg/sonatype/aether/RepositorySystem'.`

**Comment by jakenjarvis** [comment]
Hi @orospakr 
In order to build, Android Maven Plugin 3.8.0 will be required.
I plan to correspond to that in the next release.
Thank you!

**Comment by orospakr** [comment]
Thank you. :)

**Comment by jakenjarvis** [comment]
Since shifted to Gradle build, I will close this Issue. thanks! :D

**Comment by orospakr** [comment]
That's awesome.

Cheers. :)
